### ISSUE TITLE
Limit plugin to reviews, not new cards

### ISSUE THREAD

**Issue by jaksz** [jaksz/anki-blitz#2]
@corpulentcoffee , do you think it would be hard to limit this plugin to work only for reviews and not for new cards?

**Comment by corpulentcoffee** [comment]
@jaksz I _believe_ that
- `self.mw.col.sched.answerButtons(self.card) == 4` review mode
- `self.mw.col.sched.answerButtons(self.card) == 3` learning/new mode
- `self.mw.col.sched.answerButtons(self.card) == 2` review-ahead mode

**Comment by corpulentcoffee** [comment]
(So basically in the add-on's `_defaultEase`, count the buttons, and mimic or call [the original `_defaultEase`](https://github.com/dae/anki/blob/master/aqt/reviewer.py#L639) if you get something other than `4`. I haven't actually tried this yet, though.)

**Comment by corpulentcoffee** [comment]
(On second thought, `self.mw.col.sched.answerButtons(self.card) == 2` might indicate the review of a lapsed card, too... but in that case, regardless of if you're doing a review-ahead or a lapsed card, you're really just picking between "again" and "OK" based on how much time has elapsed.)

**Comment by jaksz** [comment]
Thank you!
